"""
models/source_document.py — SQLAlchemy ORM models for source_documents and document_chunks.

These mirror the tables defined in BackEnd/schema.sql. The Python service
writes to these tables; the Node service reads them for report generation.

Embeddings are generated by all-MiniLM-L6-v2 (384 dims) via sentence-transformers.
"""

import uuid
from datetime import datetime, timezone

from pgvector.sqlalchemy import Vector
from sqlalchemy import Column, DateTime, ForeignKey, String, Text, Integer
from sqlalchemy.dialects.postgresql import JSONB, UUID

from app.core.config import settings
from app.core.database import Base


class SourceDocument(Base):
    """Raw fetched document — one per article/post/video per query."""

    __tablename__ = "source_documents"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    query_id = Column(UUID(as_uuid=True), ForeignKey("queries.id", ondelete="CASCADE"), nullable=False)
    source = Column(String(50), nullable=False)          # wikipedia | reddit | youtube | ...
    author = Column(String(255), nullable=True)
    text = Column(Text, nullable=False)
    url = Column(Text, nullable=True)
    published_at = Column(DateTime(timezone=True), nullable=True)
    engagement_metrics = Column(JSONB, nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))


class DocumentChunk(Base):
    """Chunked + embedded text for RAG retrieval."""

    __tablename__ = "document_chunks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    source_document_id = Column(
        UUID(as_uuid=True),
        ForeignKey("source_documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Denormalized from source_documents — avoids a join during retrieval.
    query_id = Column(UUID(as_uuid=True), ForeignKey("queries.id", ondelete="CASCADE"), nullable=False)
    chunk_text = Column(Text, nullable=False)
    
    # ── New metadata columns for Phase C pipeline ──
    chunk_index = Column(
        Integer, 
        nullable=True, 
        comment="0-based index of this chunk within the parent document."
    )
    metadata_ = Column(
        "metadata",
        JSONB, 
        nullable=True,
        comment="Stores source_type, author, url, subreddit, video_id, etc."
    )
    
    # all-MiniLM-L6-v2 produces 384-dimensional embeddings
    embedding = Column(Vector(settings.embedding_dimension))
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
